spring:
  profiles:
    active: blue_server
    group:
      local_server: local, common, secret
      blue_server: blue, common, secret
      green_server: green, common, secret

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
  deploy-address: localhost
  name: local_server

---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080
  deploy-address: 3.39.39.112
  name: blue_server

---

spring:
  config:
    activate:
      on-profile: green

server:
  port: 9090
  deploy-address: 3.39.39.112
  name: green_server

---

spring:
  config:
    activate:
      on-profile: common

client:
  deploy-address: "localhost:3000"